[project]
name = "asteroids-project"
version = "0.1.0"
description = "A simple Asteroids game built with Pygame."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pygame==2.6.1",
]
